"""add piragi_document_paths

Revision ID: 07e747298a89
Revises: f3e2758f1158
Create Date: 2026-04-13 11:39:08.540986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07e747298a89'
down_revision: Union[str, Sequence[str], None] = 'f3e2758f1158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('piragi_document_paths', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'piragi_document_paths')
    # ### end Alembic commands ###
