"""add content_length to projects

Revision ID: 36feeadfca8f
Revises: d31d0eb96b1f
Create Date: 2026-04-18 01:10:34.351619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36feeadfca8f'
down_revision: Union[str, Sequence[str], None] = 'd31d0eb96b1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('content_length', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'content_length')
    # ### end Alembic commands ###
