"""initial

Revision ID: 9545cd70bf83
Revises: 
Create Date: 2026-04-11 19:48:13.134057

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9545cd70bf83'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('target_format', sa.String(length=20), nullable=False),
    sa.Column('content_goal', sa.String(length=20), nullable=True),
    sa.Column('raw_notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("content_goal IN ('Sell','Educate','Entertain','Build Authority') OR content_goal IS NULL", name='ck_projects_content_goal'),
    sa.CheckConstraint("status IN ('draft','in_progress','completed')", name='ck_projects_status'),
    sa.CheckConstraint("target_format IN ('VSL','YouTube','Tutorial','Facebook','LinkedIn','Blog')", name='ck_projects_target_format'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_updated_at', 'projects', [sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('icp_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('demographics', sa.Text(), nullable=False),
    sa.Column('psychographics', sa.Text(), nullable=False),
    sa.Column('pain_points', sa.Text(), nullable=False),
    sa.Column('desires', sa.Text(), nullable=False),
    sa.Column('objections', sa.Text(), nullable=False),
    sa.Column('language_style', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('generated','uploaded')", name='ck_icp_profiles_source'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('pipeline_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('step_type', sa.String(length=30), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('input_data', sa.Text(), nullable=False),
    sa.Column('output_data', sa.Text(), nullable=True),
    sa.Column('selected_option', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=20), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','completed','failed')", name='ck_pipeline_steps_status'),
    sa.CheckConstraint("step_type IN ('icp','hook','narrative','retention','cta','writer','factcheck','readability','copyright','policy')", name='ck_pipeline_steps_step_type'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'step_type', 'step_order', name='uq_project_step_type')
    )
    op.create_index('idx_pipeline_steps_project_order', 'pipeline_steps', ['project_id', 'step_order'], unique=False)
    op.create_index('idx_pipeline_steps_status', 'pipeline_steps', ['project_id', 'status'], unique=False)
    op.create_table('script_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('hook_text', sa.Text(), nullable=True),
    sa.Column('narrative_pattern', sa.String(length=50), nullable=True),
    sa.Column('retention_techniques', sa.Text(), nullable=True),
    sa.Column('cta_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version_number', name='uq_project_version')
    )
    op.create_index('idx_script_versions_project', 'script_versions', ['project_id', sa.literal_column('version_number DESC')], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('script_version_id', sa.String(length=36), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('findings', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("agent_type IN ('factcheck','readability','copyright','policy')", name='ck_analysis_results_agent_type'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'script_version_id', 'agent_type', name='uq_analysis_version_agent')
    )
    op.create_index('idx_analysis_results_project', 'analysis_results', ['project_id'], unique=False)
    op.create_index('idx_analysis_results_version', 'analysis_results', ['script_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_analysis_results_version', table_name='analysis_results')
    op.drop_index('idx_analysis_results_project', table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index('idx_script_versions_project', table_name='script_versions')
    op.drop_table('script_versions')
    op.drop_index('idx_pipeline_steps_status', table_name='pipeline_steps')
    op.drop_index('idx_pipeline_steps_project_order', table_name='pipeline_steps')
    op.drop_table('pipeline_steps')
    op.drop_table('icp_profiles')
    op.drop_index('idx_projects_updated_at', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
