"""add_draft_to_projects

Revision ID: d31d0eb96b1f
Revises: 07e747298a89
Create Date: 2026-04-14 13:10:32.591249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31d0eb96b1f'
down_revision: Union[str, Sequence[str], None] = '07e747298a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('draft', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'draft')
    # ### end Alembic commands ###
