"use client";

import { useState } from "react";
import type { CTAAgentOutput, CTASuggestion } from "@/types/agents";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import { NotebookLMContext } from "@/components/shared/notebooklm-context";

const CTA_OPTIONS = [
  { id: "subscribe", name: "Subscribe", description: "Encourage audience to subscribe to channel", why_best: "Best for building long-term audience awareness and community." },
  { id: "buy", name: "Buy", description: "Drive purchase action for product/service", why_best: "Best for product launches or promotional content." },
];

interface CTAPanelProps {
  data: CTAAgentOutput;
  onContinue: (selected: CTASuggestion) => void;
  onRerun: () => void;
  isRunning: boolean;
  projectId: string;
  stepType?: string;
  initialSelection?: CTASuggestion;
}

export function CTAPanel({ data, onContinue, onRerun, isRunning, projectId, stepType, initialSelection }: CTAPanelProps) {
  const [selectedIdx, setSelectedIdx] = useState<number | null>(() => {
    if (initialSelection) {
      return data.ctas.findIndex(c => c.text === initialSelection.text);
    }
    return null;
  });
  const [showTemplates, setShowTemplates] = useState(false);

  function handleContinue() {
    if (selectedIdx !== null && data.ctas[selectedIdx]) {
      onContinue(data.ctas[selectedIdx]);
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold">Call to Action</h3>
        <Button variant="outline" size="sm" onClick={onRerun} disabled={isRunning}>
          Re-run
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Agent Results</CardTitle>
          <CardDescription>Review the CTAs generated by the agent</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {data.ctas.map((cta, i) => (
            <button
              key={i}
              onClick={() => { setSelectedIdx(i); setShowTemplates(true); }}
              className={cn(
                "w-full rounded-lg border p-3 text-left transition-colors",
                selectedIdx === i ? "border-primary bg-primary/5" : "border-border hover:bg-muted"
              )}
            >
              <div className="flex items-center gap-2">
                <Badge variant="secondary">{cta.cta_type}</Badge>
                {selectedIdx === i && (
                  <span className="text-xs text-primary ml-auto">Selected</span>
                )}
              </div>
              <p className="mt-1 text-sm font-medium">{cta.text}</p>
              {cta.reasoning && (
                <p className="mt-1 text-xs text-muted-foreground">{cta.reasoning}</p>
              )}
            </button>
          ))}
        </CardContent>
      </Card>

      {showTemplates && (
        <Card>
          <CardHeader>
            <CardTitle>Template Options</CardTitle>
            <CardDescription>Choose CTA template types</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {CTA_OPTIONS.map((option) => (
              <button
                key={option.id}
                onClick={() => {
                  const cta: CTASuggestion = {
                    cta_type: option.id,
                    text: `Click here to ${option.name.toLowerCase()}!`,
                    reasoning: option.why_best,
                  };
                  onContinue(cta);
                }}
                className="w-full rounded-lg border border-border p-3 text-left transition-colors hover:bg-muted"
              >
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium">{option.name}</span>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{option.description}</p>
                <p className="mt-1 text-xs text-primary">{option.why_best}</p>
              </button>
            ))}
          </CardContent>
        </Card>
      )}

      {stepType !== "cta" && <NotebookLMContext stepType="cta" projectId={projectId} />}

      <div className="flex items-center justify-between">
        <p className="text-xs text-muted-foreground">Confidence: {Math.round(data.confidence * 100)}%</p>
        <Button onClick={handleContinue} disabled={selectedIdx === null}>
          Continue
        </Button>
      </div>
    </div>
  );
}