"use client";

import { useState } from "react";
import type { NarrativeAgentOutput, NarrativePattern } from "@/types/agents";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { NotebookLMContext } from "@/components/shared/notebooklm-context";

const TEMPLATE_OPTIONS = [
  { id: "aida", name: "AIDA", description: "Attention-Interest-Desire-Action", why_best: "Best for awareness stages where you need to grab attention quickly and build desire over time." },
  { id: "pas", name: "PAS", description: "Problem-Agitate-Solution", why_best: "Best for prospects who already know they have a problem and need emotional validation before solving." },
];

interface NarrativePanelProps {
  data: NarrativeAgentOutput;
  onContinue: (selected: NarrativePattern) => void;
  onRerun: () => void;
  isRunning: boolean;
  projectId: string;
  stepType?: string;
  initialSelection?: NarrativePattern;
}

export function NarrativePanel({ data, onContinue, onRerun, isRunning, projectId, stepType, initialSelection }: NarrativePanelProps) {
  const [selectedPattern, setSelectedPattern] = useState<number | null>(() => {
    if (initialSelection) {
      return data.patterns.findIndex(p => p.pattern_name === initialSelection.pattern_name);
    }
    return null;
  });
  const [showTemplates, setShowTemplates] = useState(false);

  function handleContinue() {
    if (selectedPattern !== null && data.patterns[selectedPattern]) {
      onContinue(data.patterns[selectedPattern]);
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold">Narrative Pattern</h3>
        <Button variant="outline" size="sm" onClick={onRerun} disabled={isRunning}>
          Re-run
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Agent Results</CardTitle>
          <CardDescription>Review the narrative patterns generated by the agent</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {data.patterns.map((pattern, i) => (
            <button
              key={i}
              onClick={() => { setSelectedPattern(i); setShowTemplates(true); }}
              className={cn(
                "w-full rounded-lg border p-3 text-left transition-colors",
                selectedPattern === i ? "border-primary bg-primary/5" : "border-border hover:bg-muted"
              )}
            >
              <div className="flex items-center gap-2">
                <span className="text-sm font-medium">{pattern.pattern_name}</span>
                {pattern.is_recommended && <Badge>Recommended</Badge>}
                {selectedPattern === i && (
                  <span className="text-xs text-primary ml-auto">Selected</span>
                )}
              </div>
              <p className="mt-1 text-sm text-muted-foreground">{pattern.description}</p>
              {pattern.structure.length > 0 && (
                <ul className="mt-2 list-disc pl-4 text-xs text-muted-foreground">
                  {pattern.structure.slice(0, 3).map((s, j) => (
                    <li key={j}>{s}</li>
                  ))}
                </ul>
              )}
              <p className="mt-2 text-xs text-muted-foreground">Confidence: {Math.round((pattern.confidence || 0) * 100)}%</p>
            </button>
          ))}
        </CardContent>
      </Card>

      {showTemplates && (
        <Card>
          <CardHeader>
            <CardTitle>Template Options</CardTitle>
            <CardDescription>Choose a narrative pattern template</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {TEMPLATE_OPTIONS.map((template) => (
              <button
                key={template.id}
                onClick={() => {
                  const pattern: NarrativePattern = {
                    pattern_name: template.name,
                    description: template.description,
                    fit_score: 0.9,
                    is_recommended: true,
                    structure: [],
                    confidence: 0.9,
                  };
                  onContinue(pattern);
                }}
                className="w-full rounded-lg border border-border p-3 text-left transition-colors hover:bg-muted"
              >
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium">{template.name}</span>
                  <Badge variant="secondary">{template.description}</Badge>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{template.why_best}</p>
              </button>
            ))}
          </CardContent>
        </Card>
      )}

      {stepType !== "narrative" && <NotebookLMContext stepType="narrative" projectId={projectId} />}

      <div className="flex items-center justify-between">
        <p className="text-xs text-muted-foreground">Confidence: {Math.round(data.confidence * 100)}%</p>
        <Button onClick={handleContinue} disabled={selectedPattern === null}>
          Continue
        </Button>
      </div>
    </div>
  );
}