"use client";

import { useState } from "react";
import type { RetentionAgentOutput, RetentionTechnique } from "@/types/agents";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import { NotebookLMContext } from "@/components/shared/notebooklm-context";

const TEMPLATE_OPTIONS = [
  { id: "curiosity_gap", name: "Curiosity Gap", description: "Create curiosity gaps to keep viewers watching", placement: "30% mark", why_best: "Best for mid-video retention when viewers might drop off." },
  { id: "teasers", name: "Teasers", description: "Use preview snippets to build anticipation", placement: "15% mark, close at 80%", why_best: "Best for compelling content with clear payoffs." },
];

interface RetentionPanelProps {
  data: RetentionAgentOutput;
  onContinue: (selected: RetentionTechnique[]) => void;
  onRerun: () => void;
  isRunning: boolean;
  projectId: string;
  stepType?: string;
  initialSelections?: RetentionTechnique[];
}

export function RetentionPanel({ data, onContinue, onRerun, isRunning, projectId, stepType, initialSelections }: RetentionPanelProps) {
  const [selectedIds, setSelectedIds] = useState<number[]>(() => {
    if (initialSelections && initialSelections.length > 0) {
      return initialSelections.map(selected => {
        const target = selected.technique_name?.toLowerCase();
        return data.techniques.findIndex(t => 
          t.technique_name && t.technique_name.toLowerCase() === target
        );
      }).filter(idx => idx >= 0);
    }
    return [];
  });
  const [showTemplates, setShowTemplates] = useState(false);

  function handleSelect(idx: number) {
    setSelectedIds(prev => 
      prev.includes(idx) 
        ? prev.filter(id => id !== idx)
        : [...prev, idx]
    );
  }

  function handleContinue() {
    const selected = selectedIds.map(idx => data.techniques[idx]).filter(Boolean);
    if (selected.length > 0) {
      onContinue(selected);
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold">Retention Techniques</h3>
        <Button variant="outline" size="sm" onClick={onRerun} disabled={isRunning}>
          Re-run
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Agent Results</CardTitle>
          <CardDescription>Review the retention techniques generated by the agent</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {data.techniques.length === 0 ? (
            <p className="text-sm text-muted-foreground">No techniques generated. Click Re-run to retry.</p>
          ) : data.techniques.map((technique, i) => (
            <button
              key={i}
              onClick={() => handleSelect(i)}
              className={cn(
                "w-full rounded-lg border p-3 text-left transition-colors",
                selectedIds.includes(i) ? "border-primary bg-primary/5" : "border-border hover:bg-muted"
              )}
            >
              <div className="flex items-center gap-2">
                <input 
                  type="checkbox" 
                  checked={selectedIds.includes(i)} 
                  onChange={() => handleSelect(i)}
                  className="h-4 w-4"
                />
                <span className="text-sm font-medium">{technique.technique_name}</span>
              </div>
              <p className="mt-1 text-sm text-muted-foreground">{technique.description}</p>
              <p className="mt-1 text-xs text-muted-foreground">Placement: {technique.placement_hint}</p>
            </button>
          ))}
        </CardContent>
      </Card>

      {showTemplates && (
        <Card>
          <CardHeader>
            <CardTitle>Template Options</CardTitle>
            <CardDescription>Choose retention technique templates</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {TEMPLATE_OPTIONS.map((template) => (
              <button
                key={template.id}
                onClick={() => {
                  const technique: RetentionTechnique = {
                    technique_name: template.name,
                    description: template.description,
                    placement_hint: template.placement,
                  };
                  onContinue([technique]);
                }}
                className="w-full rounded-lg border border-border p-3 text-left transition-colors hover:bg-muted"
              >
                <div className="flex items-center gap-2">
                  <span className="text-sm font-medium">{template.name}</span>
                </div>
                <p className="mt-1 text-xs text-muted-foreground">{template.description}</p>
                <p className="mt-1 text-xs text-primary">{template.why_best}</p>
              </button>
            ))}
          </CardContent>
        </Card>
      )}

      {stepType !== "retention" && <NotebookLMContext stepType="retention" projectId={projectId} />}

      <div className="flex items-center justify-between">
        <p className="text-xs text-muted-foreground">Confidence: {Math.round(data.confidence * 100)}% | Selected: {selectedIds.length}</p>
        <Button onClick={handleContinue} disabled={selectedIds.length === 0}>
          Continue ({selectedIds.length})
        </Button>
      </div>
    </div>
  );
}